export default {
    GET_CURRENT_SONG_LIST: 'GET_CURRENT_SONG_LIST', // 获取播放列表
    SET_CURRENT_PLAY_INDEX: 'SET_CURRENT_PLAY_INDEX', // 顺序播放
    SET_RANDOM_PLAYED_INDEX: 'SET_RANDOM_PLAYED_INDEX', // 随机播放过的index
    RESET_RANDOM_PLAYED_INDEX: 'RESET_RANDOM_PLAYED_INDEX', // 重置随机播放过的数组
    SET_PLAY_WAY: 'SET_PLAY_WAY', // 设置播放方式
    SET_IS_PAUSED: 'SET_IS_PAUSED', // 全局设置是否暂停

}
