export default {
    GET_CURRENT_SONG_LIST: 'GET_CURRENT_SONG_LIST', // 获取播放列表
    SET_CURRENT_PLAY_INDEX: 'SET_CURRENT_PLAY_INDEX', // 顺序播放
    SHUFFLE_LIST: 'SHUFFLE_LIST', // 洗牌
    SET_PLAY_WAY: 'SET_PLAY_WAY', // 设置播放方式

}
